services:
  api:
    build:
      context: ./douyin-api
      dockerfile: Dockerfile
    restart: always
    container_name: hatani-tiktok-new-api
    ports:
      - "8000:80" # Мы будем обращаться к API через порт 8000
    volumes:
      - ./douyin-api/config.yaml:/app/config.yaml
      - ./douyin-api/crawlers/douyin/web/config.yaml:/app/crawlers/douyin/web/config.yaml
      - ./douyin-api/crawlers/tiktok/web/config.yaml:/app/crawlers/tiktok/web/config.yaml
    environment:
      - TZ=Europe/Moscow

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    container_name: hatani-tiktok-bot
    depends_on:
      - api
    env_file:
      - ./bot/.env